// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrlunfnwzbkwahbjitqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlybHVuZm53emJrd2FoYmppdHFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNjYzMDAsImV4cCI6MjA1ODk0MjMwMH0.AWo3BQPrzMaKqmzL4638GPbxYgBJNikEfHMld6ka0vE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);